# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
  

    

    volumes:
      - .:/rails
      

    ports:
      - "3000:3000"
      

    stdin_open: true
    tty: true