
service: inventory-system
image: unyielding1/inventory-system 


servers:
  web:
    hosts:
      - 164.92.115.15 # He puesto una IP de ejemplo, REEMPLÁZALA con la tuya


registry:
  username: unyielding1 
  password:
    - KAMAL_REGISTRY_PASSWORD


env:
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY

volumes:
  - /root/storage/inventory_system:/rails/storage


proxy:
  image: traefik:v3.0
  labels:
 
    traefik.http.routers.inventory-system.rule: Host(`164.92.115.15`) 
    traefik.http.routers.inventory-system.service: inventory-system
    traefik.http.services.inventory-system.loadbalancer.server.port: 3000

builder:
  args:
    platform: linux/amd64