name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run containers

        run: docker compose up -d

      - name: Check running containers
        run: docker compose ps

      - name: Lint Ruby code (RuboCop)
        run: docker compose exec -T web bin/rubocop

      - name: Scan for Ruby vulnerabilities (Brakeman)
        run: docker compose exec -T web bin/brakeman --no-pager

      - name: Scan for JS vulnerabilities (Importmap)
        run: docker compose exec -T web bin/importmap audit

      - name: Run all tests (Controllers and System)
        run: docker compose exec -T web bin/rails test test:system

      - name: Upload screenshots on failure
      
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tmp/screenshots
          if-no-files-found: ignore